version: '3.8'

services:
  mui-practice:
    image: mui-practice:dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: mui-practice
    restart: unless-stopped
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - ./:/app
